import './globals.css';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Spacer from '@/components/spacer';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} `}>
        <nav className="flex justify-around items-center h-32 shadow-xl shadow-slate-800">
          <div className="m-auto text-4xl ml-12">
            <Link href="/">Locked Shelf</Link>
          </div>

          {/* <div className="m-auto mr-12">
            <Link href="/info">Information</Link>
          </div> */}
        </nav>
        <Spacer size={8} />
        <main>{children}</main>
        <Spacer size={32} />
        <footer className="border-t-2 backdrop-blur-xl  border-slate-800 border-opacity-70 bg-inherit opacity-80 text-sm p-8">
          copyright 2023
        </footer>
      </body>
    </html>
  );
}
