import './globals.css';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Spacer from '@/components/spacer';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <nav className="flex justify-between items-center h-32 shadow-xl shadow-slate-800">
          <div className="m-auto text-4xl">
            <Link href="/">Logo</Link>
          </div>
          <ul className="flex w-1/2 justify-around">
            <li>
              <Link href="/info">Information</Link>
            </li>
          </ul>
        </nav>
        <Spacer size={8} />
        <main>{children}</main>
        <Spacer size={32} />
        <footer className="border-t-2 fixed bottom-0 left-0 right-0 border-slate-800 border-opacity-70 bg-inherit opacity-80 backdrop-blur-3xl text-sm p-8">
          copyright 2023
        </footer>
      </body>
    </html>
  );
}
